# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ConfigSettingsInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConfigSettingsInner - a model defined in OpenAPI

        setting1: The setting1 of this ConfigSettingsInner [Optional].
        setting2: The setting2 of this ConfigSettingsInner [Optional].
    """

    setting1: Optional[str] = Field(alias="setting1", default=None)
    setting2: Optional[str] = Field(alias="setting2", default=None)

ConfigSettingsInner.update_forward_refs()
