# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.config_settings_inner import ConfigSettingsInner


class Config(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Config - a model defined in OpenAPI

        settings: The settings of this Config [Optional].
    """

    settings: Optional[List[ConfigSettingsInner]] = Field(alias="settings", default=None)

Config.update_forward_refs()
