# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ErrorResponseDetailsInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ErrorResponseDetailsInner - a model defined in OpenAPI

        field: The field of this ErrorResponseDetailsInner.
        issue: The issue of this ErrorResponseDetailsInner.
    """

    field: str = Field(alias="field")
    issue: str = Field(alias="issue")

ErrorResponseDetailsInner.update_forward_refs()
