# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ImagesDataforUserImageManipulationResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ImagesDataforUserImageManipulationResponse - a model defined in OpenAPI

        head: The head of this ImagesDataforUserImageManipulationResponse [Optional].
        headselection_mask: The headselection_mask of this ImagesDataforUserImageManipulationResponse [Optional].
        head_transparent: The head_transparent of this ImagesDataforUserImageManipulationResponse [Optional].
    """

    head: Optional[str] = Field(alias="head", default=None)
    headselection_mask: Optional[str] = Field(alias="headselection_mask", default=None)
    head_transparent: Optional[str] = Field(alias="head_transparent", default=None)

ImagesDataforUserImageManipulationResponse.update_forward_refs()
