# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.config import Config
from models.image_manipulation_request_data import ImageManipulationRequestData
from models.operation import Operation


class ImageManipulationRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ImageManipulationRequest - a model defined in OpenAPI

        operation: The operation of this ImageManipulationRequest.
        config: The config of this ImageManipulationRequest.
        data: The data of this ImageManipulationRequest.
    """

    operation: Operation = Field(alias="operation")
    config: Config = Field(alias="config")
    data: List[ImageManipulationRequestData] = Field(alias="data")

ImageManipulationRequest.update_forward_refs()
