# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class IncreaseUserLimitRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IncreaseUserLimitRequest - a model defined in OpenAPI

        user_id: The user_id of this IncreaseUserLimitRequest.
        payment_confirmation_id: The payment_confirmation_id of this IncreaseUserLimitRequest.
        new_limit: The new_limit of this IncreaseUserLimitRequest.
    """

    user_id: str = Field(alias="userId")
    payment_confirmation_id: str = Field(alias="paymentConfirmationId")
    new_limit: int = Field(alias="newLimit")

IncreaseUserLimitRequest.update_forward_refs()
