# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Operation(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Operation - a model defined in OpenAPI

        userid: The userid of this Operation [Optional].
        package_sent_time: The package_sent_time of this Operation [Optional].
        counter: The counter of this Operation [Optional].
        link: The link of this Operation [Optional].
        operation_name: The operation_name of this Operation [Optional].
    """

    userid: Optional[str] = Field(alias="userid", default=None)
    package_sent_time: Optional[str] = Field(alias="package_sent_time", default=None)
    counter: Optional[int] = Field(alias="counter", default=None)
    link: Optional[AnyUrl] = Field(alias="link", default=None)
    operation_name: Optional[str] = Field(alias="operation_name", default=None)

Operation.update_forward_refs()
