# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class RegisterUser200Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RegisterUser200Response - a model defined in OpenAPI

        message: The message of this RegisterUser200Response [Optional].
        user_id: The user_id of this RegisterUser200Response [Optional].
    """

    message: Optional[str] = Field(alias="message", default=None)
    user_id: Optional[str] = Field(alias="userId", default=None)

RegisterUser200Response.update_forward_refs()
