# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class RegisterUserRequestPlatform(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RegisterUserRequestPlatform - a model defined in OpenAPI

        os: The os of this RegisterUserRequestPlatform.
        version: The version of this RegisterUserRequestPlatform.
    """

    os: str = Field(alias="os")
    version: str = Field(alias="version")

RegisterUserRequestPlatform.update_forward_refs()
