# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.operation_status2 import OperationStatus2
from models.user_image_manipulation_response_data import UserImageManipulationResponseData


class UserImageManipulationResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UserImageManipulationResponse - a model defined in OpenAPI

        operation: The operation of this UserImageManipulationResponse [Optional].
        data: The data of this UserImageManipulationResponse [Optional].
    """

    operation: Optional[OperationStatus2] = Field(alias="operation", default=None)
    data: Optional[UserImageManipulationResponseData] = Field(alias="data", default=None)

UserImageManipulationResponse.update_forward_refs()
