# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.images_datafor_user_image_manipulation_response import ImagesDataforUserImageManipulationResponse
from models.lm_coordinates import LMCoordinates


class UserImageManipulationResponseData(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UserImageManipulationResponseData - a model defined in OpenAPI

        images: The images of this UserImageManipulationResponseData [Optional].
        fd_coordinates: The fd_coordinates of this UserImageManipulationResponseData [Optional].
        skin_color: The skin_color of this UserImageManipulationResponseData [Optional].
        lm_coordinates: The lm_coordinates of this UserImageManipulationResponseData [Optional].
    """

    images: Optional[List[ImagesDataforUserImageManipulationResponse]] = Field(alias="images", default=None)
    fd_coordinates: Optional[List[int]] = Field(alias="FD_coordinates", default=None)
    skin_color: Optional[List[int]] = Field(alias="skin_color", default=None)
    lm_coordinates: Optional[LMCoordinates] = Field(alias="LM_coordinates", default=None)

UserImageManipulationResponseData.update_forward_refs()
