# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.config_user_image_manipulation import ConfigUserImageManipulation
from models.operation import Operation
from models.v1_image_manipulations_user_post_request_data import V1ImageManipulationsUserPostRequestData


class V1ImageManipulationsUserPostRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V1ImageManipulationsUserPostRequest - a model defined in OpenAPI

        data: The data of this V1ImageManipulationsUserPostRequest.
        config: The config of this V1ImageManipulationsUserPostRequest.
        operation: The operation of this V1ImageManipulationsUserPostRequest.
    """

    data: V1ImageManipulationsUserPostRequestData = Field(alias="data")
    config: ConfigUserImageManipulation = Field(alias="config")
    operation: Operation = Field(alias="operation")

V1ImageManipulationsUserPostRequest.update_forward_refs()
