# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.images_datafor_user_image_manipulation_response import ImagesDataforUserImageManipulationResponse


class ImageManipulationResponseData(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ImageManipulationResponseData - a model defined in OpenAPI

        images: The images of this ImageManipulationResponseData [Optional].
    """

    images: Optional[List[ImagesDataforUserImageManipulationResponse]] = Field(alias="images", default=None)

ImageManipulationResponseData.update_forward_refs()
