# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.dom_image_manipulation_request_data import DOMImageManipulationRequestData
from models.image_adjustment_config import ImageAdjustmentConfig
from models.operation import Operation


class MANDOMIMAGEPostRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MANDOMIMAGEPostRequest - a model defined in OpenAPI

        data: The data of this MANDOMIMAGEPostRequest.
        config: The config of this MANDOMIMAGEPostRequest.
        operation: The operation of this MANDOMIMAGEPostRequest.
    """

    data: DOMImageManipulationRequestData = Field(alias="data")
    config: ImageAdjustmentConfig = Field(alias="config")
    operation: Operation = Field(alias="operation")

MANDOMIMAGEPostRequest.update_forward_refs()
