# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from models.config_user_image_manipulation import ConfigUserImageManipulation
from models.manusrimage_post_request_data import MANUSRIMAGEPostRequestData
from models.operation import Operation


class MANUSRIMAGEPostRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MANUSRIMAGEPostRequest - a model defined in OpenAPI

        data: The data of this MANUSRIMAGEPostRequest.
        config: The config of this MANUSRIMAGEPostRequest.
        operation: The operation of this MANUSRIMAGEPostRequest.
    """

    data: MANUSRIMAGEPostRequestData = Field(alias="data")
    config: ConfigUserImageManipulation = Field(alias="config")
    operation: Operation = Field(alias="operation")

MANUSRIMAGEPostRequest.update_forward_refs()
