# coding: utf-8

"""
    SD app

    API to communicate with SD server for variaous operations. Some useful links:  - [The repository](https://github.com/karaposu/HDILOM)  - [Confluence page](https://github.com/karaposu/HDILOM)  

    The version of the OpenAPI document: 1.0.0
    Contact: youremail@project.com
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from apis.default_api import router as DefaultApiRouter

# from impl.text_to_image import generate_image  # This is th

app = FastAPI(
    title="SD app",
    description="API to communicate with SD server for variaous operations. Some useful links:  - [The repository](https://github.com/karaposu/HDILOM)  - [Confluence page](https://github.com/karaposu/HDILOM)  ",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)

print("done")

